### ISSUE TITLE
relativeModuleId: Incorrect test.

### ISSUE THREAD

**Issue by dschnare** [amdjs/amdjs-tests#3]
In the test [relativeModuleId](https://github.com/amdjs/amdjs-tests/blob/master/tests/anon/relativeModuleId-tests.js) the assertion `t.is("util", array.utilName)` should be `t.is("impl/util", array.utilName)`.

Original Test:

```
config({
    paths: {
        "array": "impl/array"
    }
});

go(["require", "array"], function(require, array) {
        doh.register(
            "relativeModuleId",
            [
                function relativeModuleId(t){
                    t.is("impl/array", array.name);
                    t.is("util", array.utilName);
                }
            ]
        );

        doh.run();
    }
);
```

The `array` module from `impl/array.js`:

```
define(['./util'], function (util) {
    return {
        name: 'impl/array',
        utilName: util.name
    };
});
```

Note that the `array` module has a `./util` dependency relative to the _current_ module. The current module would in fact be `impl/array`, yielding a path of `impl/`, causing `./util` to be resolved to `impl/util`.

The [relativeModuleId](https://github.com/amdjs/amdjs-tests/blob/master/tests/anon/relativeModuleId-tests.js) test incorrectly assumes that the `tests/anon/util.js` file is loaded.

If this is not a bug but in fact implemented this way by design I would like to suggest changing to follow the above scenario. Following the above scenario will result in predictable relative module loading behaviour.

**Side Effect (If implementation remains the same)**

```
// This would cause our `impl/array.js` to attempt to load `arrays/are/so/great/util.js`.
config({
    paths: {
        "arrays/are/so/great": "impl/array"
    }
});

go(["require", "arrays/are/so/great"], function(require, array) {
        doh.register(
            "relativeModuleId",
            [
                function relativeModuleId(t){
                    t.is("impl/array", array.name);
                    t.is("util", array.utilName);
                }
            ]
        );

        doh.run();
    }
);
```

**Comment by dschnare** [comment]
I am going to test the above example to confirm this is the case.

**Comment by jrburke** [comment]
The test is working by design -- the test explicitly is testing that relative module IDs are resolved relative to the parent module ID and not the mapped path of the parent module ID. So if 'array' asks for './util' than the resolved module ID is 'util'. Since there is no path mapping for the 'util' module ID, it is loaded relative to the top of the baseUrl (at least baseUrl is the configuration used in requirejs).

The [API doc](https://github.com/amdjs/amdjs-api/wiki/AMD) has this text:

> The dependencies ids may be relative ids, and should be resolved relative to the module being defined.

However, it is a bit vaguely worded, and I have an action item to update the text to be more explicit. I hope to get to that soon, maybe even today.

The issue was discussed in detail in [this thread](https://groups.google.com/group/amd-implement/browse_thread/thread/c45d41ba29113d9f), where we agreed that relative IDs should be resolved relative to the module ID, not the path the parent module ID is using.

**Comment by dschnare** [comment]
James,

Thanks for clarifying. I know I'm late to the table for AMD. It took a
while for this to click in, but I agree. Rawld Gill makes a compelling
point for this approach in the thread. I now realize as well that module
IDs for anonymous modules default to the module ID used when requesting
said module and not from the module's file name. What confused me was this
bit of text in one of the examples on the AMD overview page on github:

"An anonymous module could be defined (module id derived from filename)
that returns an object literal:"

Unless I'm wrong, the anonymous module ID should default to the ID used to
load said module, correct?

-Darren S.

**Comment by jrburke** [comment]
Ah, thanks. I updated that example to remove that text. It was confusing.
