### ISSUE TITLE
Link implementations as git submodules

### ISSUE THREAD

**Issue by zevarito** [amdjs/amdjs-tests#9]
Hi,

Did you consider to add implementations into "impl" folder as git submodules to keep them up to date?

Will you accept a patch with that?

**Comment by jrburke** [comment]
I generally cannot stand git submodules because they are a mess to get set up and cause havoc when working with multiple branches. However, in this case, it may work out. I suggest contacting the [amd-implement](https://groups.google.com/group/amd-implement) list to confirm this works out for other implementers, then do the patch. 

But for what it is worth, I'm open to considering it. Although, thinking about it more, it assumes that the latest built release is in the tree at all times, I wonder if it just moves the problem to having to update the git submodules to the correct commit instead of asking implementers to keep their versions up to date -- something I'm guilty of too, although my unit tests incorporate versions of these tests.

Hmm, so yeah, I'm not tending towards not using the git submodules, but maybe a discussion on amd-implement would uncover some useful point to consider.

**Comment by thecodedrift** [comment]
With the new AMD structure, we may be able to invert the problem. For example, Inject imports the AMD test suite into their own collection: https://github.com/linkedin/inject/tree/master/tests/spec/amd in order to ensure they're compliant with the most recent specification tests.

This puts the onus on the individual framework developers, who can either use git submodules, copy over the tests, or write parallel tests like requirejs did.

**Comment by jrburke** [comment]
Sounds like there are options now, and if a project wanted to use a git submodule it could, but for inclusion in the amdjs-tests repo, just copying in the files seems to be an equivalent amount of work vs updating a submodule ref to the right commit.
